### ISSUE TITLE
Recreation of existing file share results in modifying the existing file share status as error

### ISSUE THREAD

**Issue by Shruthi-1MN** [opensds/opensds#804] opened 2019-06-01 11:02 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
If you create existing fileshare, fileshare status updates as "error"
` ` `
_root@shruthi-VirtualBox:~/opensds# curl --header "Content-Type: application/json" --data '{"name":"f3", "description":"file share test", "size":3 }' http://127.0.0.1:50040/v1beta/e93b4c0934da416eb9c8d120c5d04d96/file/shares
{"id":"df619c7b-e291-4644-9356-3d6c7d09ff49","createdAt":"2019-06-01T16:23:49","updatedAt":"2019-06-01T16:23:49","tenantId":"e93b4c0934da416eb9c8d120c5d04d96","name":"f3","description":"file share test","size":3,"availabilityZone":"default","status":"creating","profileId":"d117410c-93a1-47b7-9225-29a9a57d73bc"}
root@shruthi-VirtualBox:~/go/src/github.com/opensds/opensds# curl --header "Content-Type: application/json" --data '{"name":"f3", "description":"file share test", "size":3 }' http://127.0.0.1:50040/v1beta/e93b4c0934da416eb9c8d120c5d04d96/file/shares
{"id":"3b4fbdae-16d9-4ecc-8251-b92f15b5992d","createdAt":"2019-06-01T16:23:51","updatedAt":"2019-06-01T16:23:51","tenantId":"e93b4c0934da416eb9c8d120c5d04d96","name":"f3","description":"file share test","size":3,"availabilityZone":"default","status":"creating","profileId":"d117410c-93a1-47b7-9225-29a9a57d73bc"}
root@shruthi-VirtualBox:~/go/src/github.com/opensds/opensds# curl -X GET http://127.0.0.1:50040/v1beta/e93b4c0934da416eb9c8d120c5d04d96/file/shares/3b4fbdae-16d9-4ecc-8251-b92f15b5992d
{"id":"3b4fbdae-16d9-4ecc-8251-b92f15b5992d","createdAt":"2019-06-01T16:23:51","updatedAt":"2019-06-01T16:23:51","tenantId":"e93b4c0934da416eb9c8d120c5d04d96","name":"f3","description":"file share test","size":3,"availabilityZone":"default","status":"error","profileId":"d117410c-93a1-47b7-9225-29a9a57d73bc"}_
` ` ` 

Controller log error
------------------------
I0601 16:14:39.604517    6928 controller.go:916] controller create fleshare:  selected Driver name nfs
I0601 16:14:39.604656    6928 filesharecontroller.go:126] dock create fleshare:  connected to dock endpoint : 100.64.40.97:50050
E0601 16:14:39.613979    6928 filesharecontroller.go:130] create file share failed in file share controller:rpc error: code = Unknown desc = exit status 1
E0601 16:14:39.614033    6928 controller.go:922] when create file share:rpc error: code = Unknown desc = exit status 1

Dock Error log
------------------ 
I0601 16:16:38.421899    6899 dock.go:532] Dock server create fleshare:  sent to Driver nfs
I0601 16:16:38.421933    6899 exec.go:38] Command: env LC_ALL=C mkdir /var/f2
E0601 16:16:38.439303    6899 exec.go:41] Execute command failed
info:
mkdir: cannot create directory '/var/f2': File exists

error: exit status 1
E0601 16:16:38.439346    6899 nfs.go:139] failed to create a directory:exit status 1

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by PravinRanjan10** [comment] 2019-06-03 10:06
If a fileshare is already exist with same name. Then status should show the error. It's expected behavior. 
Because, two fileshare with same name can not exist.

**Comment by skdwriting** [comment] 2019-06-11 06:44
Please close it.

**Comment by skdwriting** [comment] 2019-06-13 07:07
Why the status is error for the original fileshare???

**Comment by skdwriting** [comment] 2019-06-14 14:07
This does not affect the existing fileshare. Hence closing this. However the DB update could be avoided with the error for the new fileshare with same name. Creating a new issue for optimization #870

**Closed by skdwriting** 2019-06-14 14:07 UTC
Labels: CAPRI, bug
